### ISSUE TITLE
Composer tag

### ISSUE THREAD

**Issue by edderrd** [cystbear/AuthorizeNet-PHP-SDK#2]
Thanks for your work on this. We are moving toward a working release of our site and need to peg composer to a specific version of this package. I understand your project is still under development, but it does carry useful features that we have come to depend on. So following recommendations made by the following sites, please create a 0.1.0 tag in this project to reflect its current level of stability.

https://igor.io/2013/01/07/composer-versioning.html

http://semver.org/

Thanks again!

**Comment by cystbear** [comment]
https://github.com/cystbear/AuthorizeNet-PHP-SDK/releases/tag/0.1.0
