### ISSUE TITLE
Why 0.1.0?

### ISSUE THREAD

**Issue by andheiberg** [cystbear/AuthorizeNet-PHP-SDK#4]
Given that payment is the perhaps most critical part of most applications having the version number be 0.1.0 kinda makes one vary of using this package.

The code looks good though, so there might not be any reason for this low number?

**Comment by cystbear** [comment]
According [SemVer](http://semver.org/) `0.1.0` looks reasonable
Also there is a lot of work to do.

**Comment by cystbear** [comment]
Ping @ajbdev
