### ISSUE TITLE
Add example to README

### ISSUE THREAD

**Issue by andheiberg** [cystbear/AuthorizeNet-PHP-SDK#5]
Please provide an example in the README.

Perhaps delete the misleading docs folder?

When I get this up and running I could perhaps provide a pull, just putting it out there now.

**Comment by cystbear** [comment]
@AndreasHeiberg yes, if you do not mind please provide PR.

**Comment by andheiberg** [comment]
I don't think I ever got it running, if I did I certainly don't remember where I saved the code :) I'm sure I would have pulled though if I actually took the time to make it work.

I'm guessing this was more of a, started using this, couldn't figure it out, here's what you could improve for people like me in the future comment.
